/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type RoleAdminChanged = ContractEventLog<{
  role: string;
  previousAdminRole: string;
  newAdminRole: string;
  0: string;
  1: string;
  2: string;
}>;
export type RoleGranted = ContractEventLog<{
  role: string;
  account: string;
  sender: string;
  0: string;
  1: string;
  2: string;
}>;
export type RoleRevoked = ContractEventLog<{
  role: string;
  account: string;
  sender: string;
  0: string;
  1: string;
  2: string;
}>;
export type SendTransaction = ContractEventLog<{
  to: string;
  data: string;
  result: string;
  0: string;
  1: string;
  2: string;
}>;
export type SendTransactionBatch = ContractEventLog<{
  to: string[];
  data: string[];
  result: string[];
  0: string[];
  1: string[];
  2: string[];
}>;
export type SetAdmin = ContractEventLog<{
  admin: string;
  account: string;
  value: boolean;
  0: string;
  1: string;
  2: boolean;
}>;
export type SetTransactor = ContractEventLog<{
  transactor: string;
  account: string;
  value: boolean;
  0: string;
  1: string;
  2: boolean;
}>;

export interface MultiTransactorAbi extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): MultiTransactorAbi;
  clone(): MultiTransactorAbi;
  methods: {
    DEFAULT_ADMIN_ROLE(): NonPayableTransactionObject<string>;

    TRANSACTOR_ROLE(): NonPayableTransactionObject<string>;

    getAdminList(
      cursor: number | string | BN,
      count: number | string | BN
    ): NonPayableTransactionObject<{
      result: string[];
      newCursor: string;
      0: string[];
      1: string;
    }>;

    getRoleAdmin(role: string | number[]): NonPayableTransactionObject<string>;

    getRoleMember(
      role: string | number[],
      index: number | string | BN
    ): NonPayableTransactionObject<string>;

    getRoleMemberCount(
      role: string | number[]
    ): NonPayableTransactionObject<string>;

    getTransactorList(
      cursor: number | string | BN,
      count: number | string | BN
    ): NonPayableTransactionObject<{
      result: string[];
      newCursor: string;
      0: string[];
      1: string;
    }>;

    grantRole(
      role: string | number[],
      account: string
    ): NonPayableTransactionObject<void>;

    hasRole(
      role: string | number[],
      account: string
    ): NonPayableTransactionObject<boolean>;

    isAdmin(account: string): NonPayableTransactionObject<boolean>;

    isTransactor(account: string): NonPayableTransactionObject<boolean>;

    renounceRole(
      role: string | number[],
      account: string
    ): NonPayableTransactionObject<void>;

    revokeRole(
      role: string | number[],
      account: string
    ): NonPayableTransactionObject<void>;

    sendTx(
      to: string,
      data: string | number[]
    ): NonPayableTransactionObject<string>;

    sendTxBatch(
      to: string[],
      data: (string | number[])[]
    ): NonPayableTransactionObject<string[]>;

    setAdmin(
      account: string,
      value: boolean
    ): NonPayableTransactionObject<boolean>;

    setTransactor(
      account: string,
      value: boolean
    ): NonPayableTransactionObject<boolean>;

    supportsInterface(
      interfaceId: string | number[]
    ): NonPayableTransactionObject<boolean>;

    version(): NonPayableTransactionObject<string>;
  };
  events: {
    RoleAdminChanged(cb?: Callback<RoleAdminChanged>): EventEmitter;
    RoleAdminChanged(
      options?: EventOptions,
      cb?: Callback<RoleAdminChanged>
    ): EventEmitter;

    RoleGranted(cb?: Callback<RoleGranted>): EventEmitter;
    RoleGranted(
      options?: EventOptions,
      cb?: Callback<RoleGranted>
    ): EventEmitter;

    RoleRevoked(cb?: Callback<RoleRevoked>): EventEmitter;
    RoleRevoked(
      options?: EventOptions,
      cb?: Callback<RoleRevoked>
    ): EventEmitter;

    SendTransaction(cb?: Callback<SendTransaction>): EventEmitter;
    SendTransaction(
      options?: EventOptions,
      cb?: Callback<SendTransaction>
    ): EventEmitter;

    SendTransactionBatch(cb?: Callback<SendTransactionBatch>): EventEmitter;
    SendTransactionBatch(
      options?: EventOptions,
      cb?: Callback<SendTransactionBatch>
    ): EventEmitter;

    SetAdmin(cb?: Callback<SetAdmin>): EventEmitter;
    SetAdmin(options?: EventOptions, cb?: Callback<SetAdmin>): EventEmitter;

    SetTransactor(cb?: Callback<SetTransactor>): EventEmitter;
    SetTransactor(
      options?: EventOptions,
      cb?: Callback<SetTransactor>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "RoleAdminChanged", cb: Callback<RoleAdminChanged>): void;
  once(
    event: "RoleAdminChanged",
    options: EventOptions,
    cb: Callback<RoleAdminChanged>
  ): void;

  once(event: "RoleGranted", cb: Callback<RoleGranted>): void;
  once(
    event: "RoleGranted",
    options: EventOptions,
    cb: Callback<RoleGranted>
  ): void;

  once(event: "RoleRevoked", cb: Callback<RoleRevoked>): void;
  once(
    event: "RoleRevoked",
    options: EventOptions,
    cb: Callback<RoleRevoked>
  ): void;

  once(event: "SendTransaction", cb: Callback<SendTransaction>): void;
  once(
    event: "SendTransaction",
    options: EventOptions,
    cb: Callback<SendTransaction>
  ): void;

  once(event: "SendTransactionBatch", cb: Callback<SendTransactionBatch>): void;
  once(
    event: "SendTransactionBatch",
    options: EventOptions,
    cb: Callback<SendTransactionBatch>
  ): void;

  once(event: "SetAdmin", cb: Callback<SetAdmin>): void;
  once(event: "SetAdmin", options: EventOptions, cb: Callback<SetAdmin>): void;

  once(event: "SetTransactor", cb: Callback<SetTransactor>): void;
  once(
    event: "SetTransactor",
    options: EventOptions,
    cb: Callback<SetTransactor>
  ): void;
}
